# Generated by Django 3.2.6 on 2021-09-05 22:11

import checkout.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='original_bag',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='order',
            name='stripe_pid',
            field=models.CharField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_delivery_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PACKING', 'Packing'), ('INTRANSIT', 'In Transit'), ('OUTFORDELIVERY', 'Out For Delivery'), ('DELIVERED', 'Delivered')], default=checkout.models.OrderDeliveryStatus['PENDING'], max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_payment_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('CONFIRMED', 'Confirmed'), ('FAILED', 'Failed')], default=checkout.models.OrderPaymentStatus['PENDING'], max_length=255),
        ),
    ]
